### ISSUE TITLE
Pandomain does not compile

### ISSUE THREAD

**Issue by lindseydew** [guardian/pan-domain-authentication#15]
This is thrown on compiling master

``` /Users/ldew/dev/workapps/pan-domain-authentication/pan-domain-auth-play_2-4-0/src/main/scala/com/gu/pandomainauth/service/googleAuthModel.scala:62: bad symbolic reference to java.time encountered in class file 'DefaultReads.class'. ```

Looks like it has been introduced by adding play 2.4.0 support

**Comment by sihil** [comment]
Guessing this was a dependency on Java 8?

**Comment by lindseydew** [comment]
Yeah...
