### ISSUE TITLE
Static name of S3 bucket: pan-domain-auth-settings

### ISSUE THREAD

**Issue by vimvim** [guardian/pan-domain-authentication#19]
S3 bucket names shared between all users in the AWS system so there is impossible to create another S3 bucket "pan-domain-auth-settings" in the another AWS accounts.

**Comment by rrees** [comment]
That's true. Feel free to contribute a patch that parameterises the name so it is easy to use another bucket name.

**Comment by piuccio** [comment]
seems like this issue can be closed, right?
